# Generated by Django 2.2 on 2021-06-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amkapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
