# Generated by Django 2.2 on 2021-06-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amkapp', '0004_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='quantity',
        ),
    ]
