# Generated by Django 2.2 on 2021-06-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amkapp', '0005_auto_20210615_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('order_id', models.CharField(max_length=100)),
                ('razorpay_payment_id', models.CharField(max_length=100)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
